spring:
  application:
    name: outfit-recommendation

  datasource:
    url: jdbc:mysql://localhost:3306/outfit_db
    username: root
    password: Chainsmokers@1902
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8089
